import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, Award, BarChart3, CircleDollarSign, MousePointerClick, Target, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { getMetaAdsDashboard } from "@/lib/meta-ads-dashboard.functions";

const usd = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });
const compact = new Intl.NumberFormat("en-US", { notation: "compact", maximumFractionDigits: 1 });

function decisionStyle(decision: string) {
  if (decision === "VENCEDOR") return "bg-emerald-500/15 text-emerald-300 border-emerald-400/30";
  if (decision === "DESPERDÍCIO") return "bg-red-500/15 text-red-300 border-red-400/30";
  if (decision === "PROMISSOR") return "bg-sky-500/15 text-sky-300 border-sky-400/30";
  return "bg-slate-500/15 text-slate-300 border-slate-400/30";
}

export function MetaAdsView({ startDate, endDate }: { startDate: string; endDate: string }) {
  const query = useQuery({ queryKey: ["meta-ads-dashboard", startDate, endDate], queryFn: () => getMetaAdsDashboard({ data: { startDate, endDate } }) });
  if (query.isLoading) return <div className="py-16 text-center text-slate-400">Carregando Meta Ads...</div>;
  const data = query.data;
  if (!data?.configured) return <Card className="bg-[#131921] border-white/10"><CardHeader><CardTitle>Meta Ads</CardTitle><CardDescription>Aguardando a primeira sincronização da conta Siding Depot.</CardDescription></CardHeader><CardContent className="text-sm text-slate-400">O painel é somente leitura e passa a exibir os dados assim que a conexão do servidor for concluída.</CardContent></Card>;
  const cards = [["Investimento", usd.format(data.totals.spend), CircleDollarSign], ["Leads", data.totals.leads.toLocaleString(), Target], ["CPL", data.totals.cpl ? usd.format(data.totals.cpl) : "—", Users], ["CTR de link", `${data.totals.ctr.toFixed(2)}%`, MousePointerClick], ["Desperdício sinalizado", usd.format(data.totals.waste), AlertTriangle]] as const;
  return <div className="space-y-6 animate-in fade-in duration-500">
    <Card className="bg-[#131921] border-white/10"><CardContent className="flex flex-col gap-1 pt-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase text-slate-400">Meta Ads · Siding Depot</p><p className="text-sm text-slate-400">Campanhas, conjuntos, anúncios e criativos no período selecionado.</p></div><p className="text-xs text-slate-500">Última sincronização: {data.lastSync?.completed_at ? new Date(data.lastSync.completed_at).toLocaleString() : "—"}</p></CardContent></Card>
    <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-5 gap-4">{cards.map(([label, value, Icon]) => <Card key={label} className="bg-[#131921] border-white/10"><CardContent className="pt-5"><Icon className="h-4 w-4 text-sd-green mb-3"/><p className="text-xs text-slate-400 uppercase font-bold">{label}</p><p className="text-xl font-black">{value}</p></CardContent></Card>)}</div>
    <div className="grid grid-cols-1 xl:grid-cols-[1.1fr_.9fr] gap-6">
      <Card className="bg-[#131921] border-white/10"><CardHeader><CardTitle className="flex gap-2 items-center"><Award className="h-5 w-5 text-sd-green"/>Criativo vencedor</CardTitle><CardDescription>Exige pelo menos {data.criteria.minLeads} leads e US$ {data.criteria.minSpend} gastos; CPL até 20% melhor que a média e CTR acima da média.</CardDescription></CardHeader><CardContent>{data.winner ? <div className="flex gap-4"><img src={data.winner.creative?.image_url || data.winner.creative?.thumbnail_url || ""} alt="Criativo vencedor" className="h-24 w-24 rounded-lg object-cover bg-white/5" onError={(event) => { event.currentTarget.style.display = "none"; }}/><div className="min-w-0"><Badge className={decisionStyle(data.winner.decision)}>{data.winner.decision}</Badge><p className="mt-2 font-bold truncate">{data.winner.name}</p><p className="text-xs text-slate-400 truncate">{data.winner.campaignName} · {data.winner.adsetName}</p><div className="mt-3 flex gap-4 text-sm"><span><b>{data.winner.leads}</b> leads</span><span><b>{usd.format(data.winner.cpl)}</b> CPL</span><span><b>{data.winner.ctr.toFixed(2)}%</b> CTR</span></div></div></div> : <p className="text-sm text-slate-400">Ainda não há volume suficiente para declarar um vencedor com segurança.</p>}</CardContent></Card>
      <Card className="bg-[#131921] border-white/10"><CardHeader><CardTitle>Leitura da conta</CardTitle><CardDescription>Decisões baseadas no desempenho do período, não em opinião.</CardDescription></CardHeader><CardContent className="grid grid-cols-2 gap-4 text-sm"><div><p className="text-slate-400">Impressões</p><p className="text-xl font-black">{compact.format(data.totals.impressions)}</p></div><div><p className="text-slate-400">Alcance</p><p className="text-xl font-black">{compact.format(data.totals.reach)}</p></div><div><p className="text-slate-400">CPC de link</p><p className="text-xl font-black">{data.totals.cpc ? usd.format(data.totals.cpc) : "—"}</p></div><div><p className="text-slate-400">CPM</p><p className="text-xl font-black">{data.totals.cpm ? usd.format(data.totals.cpm) : "—"}</p></div></CardContent></Card>
    </div>
    <Card className="bg-[#131921] border-white/10"><CardHeader><CardTitle className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-sd-green"/>Anúncios e criativos</CardTitle><CardDescription>“Desperdício” = gasto relevante sem lead ou CPL 50% acima da média. Use para pausar, revisar ou trocar criativo.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b border-white/10 text-left text-xs uppercase text-slate-400"><tr><th className="pb-3">Anúncio / criativo</th><th className="pb-3">Decisão</th><th className="pb-3 text-right">Gasto</th><th className="pb-3 text-right">Leads</th><th className="pb-3 text-right">CPL</th><th className="pb-3 text-right">CTR</th><th className="pb-3 text-right">Frequência</th></tr></thead><tbody>{data.ads.slice(0, 30).map((ad: any) => <tr key={ad.id} className="border-b border-white/5"><td className="py-3 pr-4"><div className="flex items-center gap-3">{(ad.creative?.thumbnail_url || ad.creative?.image_url) && <img src={ad.creative.image_url || ad.creative.thumbnail_url} alt="" className="h-9 w-9 rounded object-cover"/>}<div className="min-w-0"><p className="font-bold truncate max-w-[300px]">{ad.name}</p><p className="text-xs text-slate-400 truncate max-w-[300px]">{ad.campaignName} · {ad.adsetName}</p></div></div></td><td className="py-3"><Badge className={decisionStyle(ad.decision)}>{ad.decision}</Badge></td><td className="py-3 text-right">{usd.format(ad.spend)}</td><td className="py-3 text-right">{ad.leads}</td><td className="py-3 text-right">{ad.cpl ? usd.format(ad.cpl) : "—"}</td><td className="py-3 text-right">{ad.ctr.toFixed(2)}%</td><td className="py-3 text-right">{ad.frequency.toFixed(2)}</td></tr>)}</tbody></table></div></CardContent></Card>
    <Card className="bg-[#131921] border-white/10"><CardHeader><CardTitle>Campanhas</CardTitle></CardHeader><CardContent><div className="space-y-3">{data.campaigns.slice(0, 15).map((campaign: any) => <div key={campaign.id} className="grid grid-cols-[1fr_auto_auto] gap-4 border-b border-white/5 pb-3 text-sm"><div><p className="font-bold">{campaign.name}</p><p className="text-xs text-slate-400">{campaign.objective || "—"} · {campaign.status || "—"}</p></div><div className="text-right"><p>{usd.format(campaign.spend)}</p><p className="text-xs text-slate-400">{campaign.clicks.toLocaleString()} cliques</p></div><div className="text-right text-sd-green font-bold">{campaign.leads} leads</div></div>)}</div></CardContent></Card>
  </div>;
}
